name: basic steps
on: [push]
jobs:
  echo-name:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: ssh -i ~/.ssh/github_action_Stretch_key hello-robot@98.234.153.4 -p 43770