name: basic steps
on: [push]
jobs:
  echo-name:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: ssh ${{ secrets.STRETCH_SSH_KEY_GITHUB_ACTION }} hello-robot@98.234.153.4 -p 43770