name: basic steps
on: [push]
jobs:
  ssh-connection-teleop:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: save the key to file
        run: 'echo "$SSH_KEY" > the_key'
        shell: bash
        env:
          SSH_KEY: ${{ secrets.STRETCH_SSH_KEY_GITHUB_ACTION }}
      - run: cat the_key
      - run: chmod 400 the_key
      - name: Log into stretch using ssh
        run: cat the_key ;ssh -i the_key hello-robot@98.234.153.4 -p 43770 -tt -o StrictHostKeyChecking=no
      - name: output file content of setup.py in stretch body
        run: cat repos/stretch_body/body/setup.py
      - run: exit